apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx-app
spec:
  replicas: 3
  selector:
    app: myapp
  template:
    metadata:
      name: nginx-app
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
